### ISSUE TITLE
Generator fails on C#6 Expression-Bodied Members

### ISSUE THREAD

**Issue by DustinTheDev** [ALM-Rangers/Breakpoint-Generator#3]
### Installed product versions
- Visual Studio: 2015 Ultimate and 2017 Professional
- This extension: 1.1

### Description
Null reference exception thrown when parsing the public entry points for Expression-Bodied Members.

### Steps to recreate
Run with extension on a project with the below class:
```c#
public class Class1
{
  public string TestString => "My Test String";
}
```

**Comment by wpschaub** [comment]
@onlyutkarsh @jakobehn should we add this on our backlog as a new feature, or bug?

**Comment by jakobehn** [comment]
I would classify this as a bug

**Comment by wpschaub** [comment]
OK, raised and linked to bug 13381.

**Comment by jeffrey-opdam** [comment]
Closing issues, as the project is deprecated
