### ISSUE TITLE
vs crashes generating breakpoints in a dotnet core library

### ISSUE THREAD

**Issue by lucamorelli** [ALM-Rangers/Breakpoint-Generator#4]
### Installed product versions
- Visual Studio: [example 2017.3 Preview]
- This extension: [example 1.1]

### Description
I tried the extension with a dot net framework library and seems to work, though I noticed if I generate breakpoints in 2 ore more classes, only one is shown in the list windows. If I try to generate breakpoints in a dot net core class library vs crashes without any message.

### Steps to recreate
1. Select a class inside a dot net core library
2. press the generate breakpoint button.

**Comment by jeffrey-opdam** [comment]
Closing issues, as the project is deprecated
