### ISSUE TITLE
Crashes VS

### ISSUE THREAD

**Issue by dudeNumber4** [ALM-Rangers/Breakpoint-Generator#8]
### Installed product versions
- Visual Studio 2017 Professional
- This extension: 1.2

### Description
Right click on cs file in solution explorer -> Generate Breakpoints.  VS crashes

### Steps to recreate
1. See description

Event log export and windows crash output (the file referenced from the windows crash entry in the event log) attached.

[Report-change-ext-to-wer.txt](https://github.com/ALM-Rangers/Breakpoint-Generator/files/2311753/Report-change-ext-to-wer.txt)
[BreakpointGeneratorCrash-change-ext-to-evtx.txt](https://github.com/ALM-Rangers/Breakpoint-Generator/files/2311754/BreakpointGeneratorCrash-change-ext-to-evtx.txt)

**Comment by jeffrey-opdam** [comment]
Closing issues, as the project is deprecated
